petshop/pets/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from pets.views import PetsCreateView, PetsListView, PetsUpdateView, PetsDeleteView

app_name = 'pets'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /cadastrar
    path('cadastrar/', PetsCreateView.as_view(), name="cadastra_pets"),

    # GET /listar
    path('listar/', PetsListView.as_view(), name="lista_pets"),

    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /pets (pets está definido em url.py petshop)/{pk do objeto}
    path('<pk>', PetsUpdateView.as_view(), name="atualiza_pets"),

    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /pets (pets está definido em url.py petshop)/excluir/{pk do objeto}
    path('excluir/<pk>', PetsDeleteView.as_view(), name="deleta_pets"),
]

petshop/petshop/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    # Interface administrativa.
    path('admin/', admin.site.urls),

    # Inclui as URLs do app 'website'.
    path('', include('website.urls', namespace='website')),

    # Inclui as URLs do app 'services'.
    path('services/', include('services.urls', namespace='services')),

    # Inclui as URLs do app 'pets'.
    path('pets/', include('pets.urls', namespace='pets')),

        # Inclui as URLs do app 'sales'.
    path('sales/', include('sales.urls', namespace='sales')),

    # Inclui as URLs do app 'accounts'
    path('accounts/', include('accounts.urls')),

    # Inclui as URLs de 'login'
    path('accounts/', include('django.contrib.auth.urls')),
]

petshop/sales/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from sales.views import SalesCreateView, SalesListView,SalesUpdateView, SalesDeleteView

app_name = 'sales'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /cadastrar
    path('cadastrar/', SalesCreateView.as_view(), name="cadastra_sales"),

     # GET /listar
    path('listar/', SalesListView.as_view(), name="lista_sales"),

    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /sales/{pk do objeto}
    path('sales/<pk>', SalesUpdateView.as_view(), name = "atualiza_sales"),
    
    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /sales/excluir/{pk do objeto}
    path('sales/excluir/<pk>', SalesDeleteView.as_view(), name="deleta_sales"),
]

petshop/services/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from services.views import ServicesCreateView, ServicesListView, ServicesUpdateView, ServicesDeleteView

app_name = 'services'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /cadastrar
    path('cadastrar/', ServicesCreateView.as_view(), name="cadastra_services"),

    # GET /listar
    path('listar/', ServicesListView.as_view(), name="lista_services"),

    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /services (services está definido em url.py petshop)/{pk do objeto}
    path('<pk>', ServicesUpdateView.as_view(), name="atualiza_services"),

    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /services (services está definido em url.py petshop)/excluir/{pk do objeto}
    path('excluir/<pk>', ServicesDeleteView.as_view(), name="deleta_services"),
]

petshop/website/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from website.views import IndexTemplateView, ClientesListView, ClientesUpdateView, ClientesDeleteView, ClientesCreateView

app_name = 'website'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),
    
    # GET /clientes/cadastrar
    path('clientes/cadastrar', ClientesCreateView.as_view(), name="cadastra_clientes"),
    
    # GET /clientes
    path('clientes/', ClientesListView.as_view(), name="lista_clientes"),
    
    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /cliente/{pk do objeto}
    path('clientes/<pk>', ClientesUpdateView.as_view(), name = "atualiza_clientes"),
    
    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /cliente/excluir/{pk do objeto}
    path('clientes/excluir/<pk>', ClientesDeleteView.as_view(), name="deleta_clientes"),
]

petshop/website/forms.py
from petshop.models import Clientes
from django import forms

# Formulário de inserção usando ModelForm.
class InsereClientesForm(forms.ModelForm):
    class Meta:
        # Modelo que o Django deve pegar os campos.
        model = Clientes
        # Os campos que estarão no formulário serão apresentados através do atributo fields.
        fields = [
            'nome',
            'cpf',
            'telefone',
            'email',
            'endereco'
        ]

petshop/website/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from petshop.models import Clientes
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy
from website.forms import InsereClientesForm


# Impedir acesso se não estiver logado.
@method_decorator(login_required, name='dispatch')
# Utilizando a TemplateView para rederização da página.
class IndexTemplateView(TemplateView):
    template_name = "website/index.html"


@method_decorator(login_required, name='dispatch')
# Utilizando a ListView para a listagem de clientes.
class ClientesListView(ListView):
    template_name = "website/lista.html"
    model = Clientes
    context_object_name = 'clientes'


@method_decorator(login_required, name='dispatch')
# Utilizando a CreateView para adicionar um novo cliente.
class ClientesCreateView (CreateView):
    template_name = "website/cria.html"
    model = Clientes
    form_class = InsereClientesForm
    # O método reverse_lazy() vai traduzir a View em URL. Após adicionar um cliente, haverá um redirecionamento para a página de listagem atualizada.
    success_url = reverse_lazy("website:lista_clientes")


@method_decorator(login_required, name='dispatch')
# Utilizando a UpdateView para a atualização de clientes.
class ClientesUpdateView(UpdateView):
    template_name = "website/atualiza.html"
    model = Clientes
    # fields = ['nome', 'cpf', 'telefone', 'email', 'endereco']
    fields = '__all__'
    context_object_name = 'clientes'
    success_url = reverse_lazy("website:lista_clientes")


@method_decorator(login_required, name='dispatch')
# Utilizando a DeleteView para deletar um cliente.
class ClientesDeleteView(DeleteView):
    template_name = "website/exclui.html"
    model = Clientes
    context_object_name = 'clientes'
    success_url = reverse_lazy("website:lista_clientes")

petshop/website/templates/website/_layouts/base.html
<!DOCTYPE html>
{% load static %}
{# O template base.html contém o código HTML que irá se repetir em todas as páginas #}

<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/2f25f30753.js" crossorigin="anonymous"></script>
    <title>
        {% block title %}Petshop{% endblock %}
    </title>

    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">

    {% block styles %}
    {% endblock %}
</head>

<body class="bg-dark bg-img">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'website:index' %}"><strong>MEU PETSHOP</strong></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-link" aria-current="page" href="{% url 'website:index' %}">Início</a>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Todos os registros
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'website:lista_clientes' %}">Clientes</a></li>
                            <li><a class="dropdown-item" href="{% url 'pets:lista_pets' %}">Pets</a></li>
                            <li><a class="dropdown-item" href="{% url 'services:lista_services' %}">Serviços</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'sales:lista_sales' %}">Vendas</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <a class="nav-link" href="/accounts/login">Entrar</a>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="/accounts/logout">Sair</a>
                    {% endif %}
                </div>
            </div>
    </nav>

    {% block content %}
    {% endblock %}

    <!--
    <footer class="bg-light text-end text-lg-start fixed-bottom">
        <div class="text-end p-2" style="background-color: rgba(0, 0, 0, 0.1);">
            <div onchange="color(this.value)">
                <span>CORES</span>
                <a href="#" id="interruptor"><i class="link-light fas fa-circle"></i></a>
            </div>
        </div>
    </footer>
    -->

    <!-- Scripts -->
    <script src="{% static 'website/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'website/js/jquery.min.js' %}"></script>
    <script src="{% static 'website/js/scripts.js' %}"></script>

    {% block scripts %}
    {% endblock %}
</body>

</html>