petshop/pets/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from pets.views import PetsCreateView, PetsListView, PetsUpdateView, PetsDeleteView

app_name = 'pets'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /cadastrar
    path('cadastrar/', PetsCreateView.as_view(), name="cadastra_pets"),

    # GET /listar
    path('listar/', PetsListView.as_view(), name="lista_pets"),

    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /pets (pets está definido em url.py petshop)/{pk do objeto}
    path('<pk>', PetsUpdateView.as_view(), name="atualiza_pets"),

    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /pets (pets está definido em url.py petshop)/excluir/{pk do objeto}
    path('excluir/<pk>', PetsDeleteView.as_view(), name="deleta_pets"),
]

petshop/petshop/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    # Interface administrativa.
    path('admin/', admin.site.urls),

    # Inclui as URLs do app 'website'.
    path('', include('website.urls', namespace='website')),

    # Inclui as URLs do app 'services'.
    path('services/', include('services.urls', namespace='services')),

    # Inclui as URLs do app 'pets'.
    path('pets/', include('pets.urls', namespace='pets')),

        # Inclui as URLs do app 'sales'.
    path('sales/', include('sales.urls', namespace='sales')),

    # Inclui as URLs do app 'accounts'
    path('accounts/', include('accounts.urls')),

    # Inclui as URLs de 'login'
    path('accounts/', include('django.contrib.auth.urls')),
]

petshop/sales/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from sales.views import SalesCreateView, SalesListView,SalesUpdateView, SalesDeleteView

app_name = 'sales'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /cadastrar
    path('cadastrar/', SalesCreateView.as_view(), name="cadastra_sales"),

     # GET /listar
    path('listar/', SalesListView.as_view(), name="lista_sales"),

    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /sales/{pk do objeto}
    path('sales/<pk>', SalesUpdateView.as_view(), name = "atualiza_sales"),
    
    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /sales/excluir/{pk do objeto}
    path('sales/excluir/<pk>', SalesDeleteView.as_view(), name="deleta_sales"),
]

petshop/services/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from services.views import ServicesCreateView, ServicesListView, ServicesUpdateView, ServicesDeleteView

app_name = 'services'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /cadastrar
    path('cadastrar/', ServicesCreateView.as_view(), name="cadastra_services"),

    # GET /listar
    path('listar/', ServicesListView.as_view(), name="lista_services"),

    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /services (services está definido em url.py petshop)/{pk do objeto}
    path('<pk>', ServicesUpdateView.as_view(), name="atualiza_services"),

    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /services (services está definido em url.py petshop)/excluir/{pk do objeto}
    path('excluir/<pk>', ServicesDeleteView.as_view(), name="deleta_services"),
]

petshop/website/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from website.views import IndexTemplateView, ClientesListView, ClientesUpdateView, ClientesDeleteView, ClientesCreateView

app_name = 'website'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),
    
    # GET /clientes/cadastrar
    path('clientes/cadastrar', ClientesCreateView.as_view(), name="cadastra_clientes"),
    
    # GET /clientes
    path('clientes/', ClientesListView.as_view(), name="lista_clientes"),
    
    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /cliente/{pk do objeto}
    path('clientes/<pk>', ClientesUpdateView.as_view(), name = "atualiza_clientes"),
    
    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /cliente/excluir/{pk do objeto}
    path('clientes/excluir/<pk>', ClientesDeleteView.as_view(), name="deleta_clientes"),
]

petshop/website/forms.py
from petshop.models import Clientes
from django import forms

# Formulário de inserção usando ModelForm.
class InsereClientesForm(forms.ModelForm):
    class Meta:
        # Modelo que o Django deve pegar os campos.
        model = Clientes
        # Os campos que estarão no formulário serão apresentados através do atributo fields.
        fields = [
            'nome',
            'cpf',
            'telefone',
            'email',
            'endereco'
        ]

petshop/website/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from petshop.models import Clientes
from django.views.generic import TemplateView, ListView, UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy
from website.forms import InsereClientesForm


# Impedir acesso se não estiver logado.
@method_decorator(login_required, name='dispatch')
# Utilizando a TemplateView para rederização da página.
class IndexTemplateView(TemplateView):
    template_name = "website/index.html"


@method_decorator(login_required, name='dispatch')
# Utilizando a ListView para a listagem de clientes.
class ClientesListView(ListView):
    template_name = "website/lista.html"
    model = Clientes
    context_object_name = 'clientes'


@method_decorator(login_required, name='dispatch')
# Utilizando a CreateView para adicionar um novo cliente.
class ClientesCreateView (CreateView):
    template_name = "website/cria.html"
    model = Clientes
    form_class = InsereClientesForm
    # O método reverse_lazy() vai traduzir a View em URL. Após adicionar um cliente, haverá um redirecionamento para a página de listagem atualizada.
    success_url = reverse_lazy("website:lista_clientes")


@method_decorator(login_required, name='dispatch')
# Utilizando a UpdateView para a atualização de clientes.
class ClientesUpdateView(UpdateView):
    template_name = "website/atualiza.html"
    model = Clientes
    # fields = ['nome', 'cpf', 'telefone', 'email', 'endereco']
    fields = '__all__'
    context_object_name = 'clientes'
    success_url = reverse_lazy("website:lista_clientes")


@method_decorator(login_required, name='dispatch')
# Utilizando a DeleteView para deletar um cliente.
class ClientesDeleteView(DeleteView):
    template_name = "website/exclui.html"
    model = Clientes
    context_object_name = 'clientes'
    success_url = reverse_lazy("website:lista_clientes")

petshop/website/templates/website/atualiza.html
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Clientes{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Atualizar cliente</h5>
                    <p class="card-text mb-4">Atualizar os dados do cliente já registrado.</p>

                    <form method="post" class="row g-3">
                        <!-- A tag do Django {% csrf_token %} está relacionada à proteção que o Django provê ao CSRF - Cross Site Request Forgery (um tipo de ataque malicioso) -->
                        {% csrf_token %}

                        <!-- Nome -->
                        <div class="col-md-8">
                            <label for="inputName" class="form-label">Nome</label>
                            {% render_field form.nome class+="form-control" %}
                        </div>

                        <!-- CPF -->
                        <div class="col-md-4">
                            <label for="inputCPF" class="form-label">CPF</label>
                            {% render_field form.cpf class+="form-control" %}
                        </div>

                        <!-- Email -->
                        <div class="col-md-8">
                            <label for="inputEmail" class="form-label">Email</label>
                            {% render_field form.email class+="form-control" %}
                        </div>

                        <!-- Telefone -->
                        <div class="col-md-4">
                            <label for="inputCelular" class="form-label">Telefone</label>
                            {% render_field form.telefone class+="form-control" %}
                        </div>

                        <!-- Endereço -->
                        <div class="col-md-12">
                            <label for="inputEndereco" class="form-label">Endereço</label>
                            {% render_field form.endereco class+="form-control" %}
                        </div>

                        <div class="text-start mt-4">
                            <button class="btn btn-secondary"><i class="fas fa-save me-2"></i>SALVAR</button>
                            <a href="{% url 'website:lista_clientes' %}"
                                class="btn btn-link text-decoration-none text-secondary">CANCELAR</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

petshop/website/templates/website/cria.html
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Clientes{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Registrar cliente</h5>
                    <p class="card-text mb-4">Use os campos abaixo para registrar um novo cliente.</p>

                    <form method="post" class="row g-3">
                        <!-- A tag do Django {% csrf_token %} está relacionada à proteção que o Django provê ao CSRF - Cross Site Request Forgery (um tipo de ataque malicioso) -->
                        {% csrf_token %}

                        <!-- Nome -->
                        <div class="col-md-8">
                            <label for="inputName" class="form-label">Nome*</label>
                            {% render_field form.nome class+="form-control" %}
                        </div>

                        <!-- CPF -->
                        <div class="col-md-4">
                            <label for="inputCPF" class="form-label">CPF*</label>
                            {% render_field form.cpf class+="form-control" %}
                        </div>

                        <!-- Email -->
                        <div class="col-md-8">
                            <label for="inputEmail" class="form-label">Email*</label>
                            {% render_field form.email class+="form-control" %}
                        </div>

                        <!-- Telefone -->
                        <div class="col-md-4">
                            <label for="inputCelular" class="form-label">Telefone*</label>
                            {% render_field form.telefone class+="form-control" %}
                        </div>

                        <!-- Endereço -->
                        <div class="col-md-12">
                            <label for="inputEndereco" class="form-label">Endereço*</label>
                            {% render_field form.endereco class+="form-control" %}
                        </div>

                        <div class="text-start mt-4">
                            <button class="btn btn-secondary"><i class="fas fa-save me-2"></i>SALVAR</button>
                            <a href="{% url 'website:index' %}"
                                class="btn btn-link text-decoration-none text-secondary">CANCELAR</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

petshop/website/templates/website/exclui.html
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% block title %}Deletar Serviço{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row d-flex justify-content-center">
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
      <div class="card bg-light border-0 mb-3">
        <div class="card-body text-dark">
          <h5 class="card-title">Exclusão de cliente</h5>
          <p class="card-text mb-4">Você tem certeza de que quer apagar o cadastro de <strong>{{ clientes.nome }}</strong>? A exclusão será irreversível.</p>

          <form method="post">
            <!-- A tag do Django {% csrf_token %} está relacionada à proteção que o Django provê ao CSRF - Cross Site Request Forgery (um tipo de ataque malicioso) -->
            {% csrf_token %}

            <div class="text-start">
              <button class="btn btn-danger"><i class="fas fa-trash-alt me-2"></i>EXCLUIR</button>
              <a href="{% url 'website:lista_clientes' %}" class="btn btn-link text-decoration-none text-secondary">CANCELAR</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

petshop/website/templates/website/index.html
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o título da página inicial -->
{% block title %}Página Inicial{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Novo Cliente</h5>
                    <p class="card-text mb-4">Acesse o formulário para cadastrar um novo cliente.</p>
                    <a class="btn btn-secondary btn-lg d-grid gap-2" href="{% url 'website:cadastra_clientes' %}"> <i
                            class="fas fa-plus"></i></a>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Novo Pet</h5>
                    <p class="card-text mb-4">Registrar um novo pet para um cliente já existente.</p>
                    <a class="btn btn-secondary btn-lg d-grid gap-2" href="{% url 'pets:cadastra_pets' %}"><i
                        class="fas fa-plus"></i></a>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Novo Serviço</h5>
                    <p class="card-text mb-4">Acrescentar uma nova opção à sua lista de serviços.</p>
                    <a class="btn btn-secondary btn-lg d-grid gap-2" href="{% url 'services:cadastra_services' %}"> <i
                            class="fas fa-plus"></i></a>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Nova Venda</h5>
                    <p class="card-text mb-4">Fazer um registro de venda para um cliente já existente.</p>
                    <a class="btn btn-secondary btn-lg d-grid gap-2" href="{% url 'sales:cadastra_sales' %}"><i
                        class="fas fa-plus"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

petshop/website/templates/website/lista.html
<!-- Aqui terá um objeto chamado 'clientes' contendo todos os clientes disponíveis para iteração. -->
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Clientes{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Lista de clientes</h5>
                    <p class="card-text mb-4">Quadro atualizado de clientes cadastrados.</p>

                    {% if clientes|length > 0 %}
                    <table class="table table-borderless">
                        <thead class="table-success">
                            <tr>
                                <th scope="col">Nome</th>
                                <!-- <th scope="col">CPF</th> -->
                                <!-- <th scope="col">Email</th> -->
                                <th scope="col">Telefone</th>
                                <th scope="col">Endereço</th>
                                <th scope="col" class="text-end">Opções</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for clientes in clientes %}
                            <tr>
                                <td>{{ clientes.nome }}</td>
                                <!-- <td>{{ clientes.cpf }}</td> -->
                                <!-- <td>{{ clientes.email }}</td> -->
                                <td>{{ clientes.telefone }}</td>
                                <td>{{ clientes.endereco }}</td>

                                <td class="text-end">
                                    <a href="{% url 'website:atualiza_clientes' pk=clientes.id %}">
                                        <i class="link-success fas fa-user-edit"></i></a>
                                    <a href="{% url 'website:deleta_clientes' pk=clientes.id %}">
                                        <i class="ms-2 link-danger fas fa-user-minus"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <div class="text-center mt-5 mb-5 jumbotron">
                        <h5>Sem clientes registrados ainda.</h5>
                    </div>
                    {% endif %}
                    <div class="text-start">
                        <a href="{% url 'website:cadastra_clientes' %}" class="btn btn-secondary"><i class="fas fa-plus me-2"></i>NOVO</a>
                        <a href="{% url 'website:index' %}" class="btn btn-link text-decoration-none text-secondary">INÍCIO</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}