petshop/pets/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from pets.views import PetsCreateView, PetsListView, PetsUpdateView, PetsDeleteView

app_name = 'pets'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /cadastrar
    path('cadastrar/', PetsCreateView.as_view(), name="cadastra_pets"),

    # GET /listar
    path('listar/', PetsListView.as_view(), name="lista_pets"),

    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /pets (pets está definido em url.py petshop)/{pk do objeto}
    path('<pk>', PetsUpdateView.as_view(), name="atualiza_pets"),

    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /pets (pets está definido em url.py petshop)/excluir/{pk do objeto}
    path('excluir/<pk>', PetsDeleteView.as_view(), name="deleta_pets"),
]

petshop/petshop/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    # Interface administrativa.
    path('admin/', admin.site.urls),

    # Inclui as URLs do app 'website'.
    path('', include('website.urls', namespace='website')),

    # Inclui as URLs do app 'services'.
    path('services/', include('services.urls', namespace='services')),

    # Inclui as URLs do app 'pets'.
    path('pets/', include('pets.urls', namespace='pets')),

        # Inclui as URLs do app 'sales'.
    path('sales/', include('sales.urls', namespace='sales')),

    # Inclui as URLs do app 'accounts'
    path('accounts/', include('accounts.urls')),

    # Inclui as URLs de 'login'
    path('accounts/', include('django.contrib.auth.urls')),
]

petshop/website/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from website.views import IndexTemplateView, ClientesListView, ClientesUpdateView, ClientesDeleteView, ClientesCreateView

app_name = 'website'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),
    
    # GET /clientes/cadastrar
    path('clientes/cadastrar', ClientesCreateView.as_view(), name="cadastra_clientes"),
    
    # GET /clientes
    path('clientes/', ClientesListView.as_view(), name="lista_clientes"),
    
    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /cliente/{pk do objeto}
    path('clientes/<pk>', ClientesUpdateView.as_view(), name = "atualiza_clientes"),
    
    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /cliente/excluir/{pk do objeto}
    path('clientes/excluir/<pk>', ClientesDeleteView.as_view(), name="deleta_clientes"),
]

petshop/pets/forms.py
from petshop.models import Pet
from django import forms


# Formulário de inserção usando ModelForm.
class InserePetsForm(forms.ModelForm):
    notas = forms.CharField(label="Observações", widget=forms.Textarea(attrs={'rows':3}))
    class Meta:
        # Modelo que o Django deve pegar os campos.
        model = Pet
        # Os campos que estarão no formulário serão apresentados através do atributo fields.
        fields = [
            'nome',
            'especie',
            'raca',
            'sexo',
            'notas',
            'cliente'
        ]

petshop/pets/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from petshop.models import Pet
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy
from pets.forms import InserePetsForm


# Impedir acesso se não estiver logado.
@method_decorator(login_required, name='dispatch')
# Utilizando a CreateView para adicionar um novo pet.
class PetsCreateView(CreateView):
    template_name = "pets/cria.html"
    model = Pet
    form_class = InserePetsForm
    # O método reverse_lazy() vai traduzir a View em URL. Após adicionar um pet, haverá um redirecionamento para a página de listagem atualizada.
    success_url = reverse_lazy("pets:lista_pets")


@method_decorator(login_required, name='dispatch')
# Utilizando a ListView para a listagem de pets.
class PetsListView(ListView):
    template_name = "pets/lista.html"
    model = Pet
    context_object_name = 'pets'


@method_decorator(login_required, name='dispatch')
# Utilizando a UpdateView para a atualização de pets.
class PetsUpdateView(UpdateView):
    template_name = "pets/atualiza.html"
    model = Pet
    # fields = ['nome', 'especie', 'raca', 'sexo', 'notas', 'cliente']
    fields = '__all__'
    context_object_name = 'pets'
    success_url = reverse_lazy("pets:lista_pets")


@method_decorator(login_required, name='dispatch')
# Utilizando a DeleteView para deletar um pet.
class PetsDeleteView(DeleteView):
    template_name = "pets/exclui.html"
    model = Pet
    context_object_name = 'pets'
    success_url = reverse_lazy("pets:lista_pets")

petshop/pets/templates/pets/atualiza.html
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% load crispy_forms_tags %}

{% block title %}Cadastro de Pets{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Atualizar pet</h5>
                    <p class="card-text mb-4">Atualização dos dados cadastrais do pet.</p>

                    <form method="post" class="row g-3">
                        <!-- A tag do Django {% csrf_token %} está relacionada à proteção que o Django provê ao CSRF - Cross Site Request Forgery (um tipo de ataque malicioso) -->
                        {% csrf_token %}

                        <!-- {{ form.as_p }} -->
                        {{ form|crispy }}

                        <div class="text-start mt-4">
                            <button class="btn btn-secondary"><i class="fas fa-save me-2"></i>SALVAR</button>
                            <a href="{% url 'pets:lista_pets' %}"
                                class="btn btn-link text-decoration-none text-secondary">CANCELAR</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

petshop/pets/templates/pets/cria.html
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% load crispy_forms_tags %}

{% block title %}Cadastro de Pets{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Registrar pet</h5>
                    <p class="card-text mb-4">Observe que, para registrar um novo animal de estimação, seu proprietário
                        deve estar previamente registrado.</p>

                    <form method="post" class="row g-3">
                        <!-- A tag do Django {% csrf_token %} está relacionada à proteção que o Django provê ao CSRF - Cross Site Request Forgery (um tipo de ataque malicioso) -->
                        {% csrf_token %}

                        <!-- {{ form.as_p }} -->
                        {{ form|crispy }}

                        <div class="text-start mt-4">
                            <button class="btn btn-secondary"><i class="fas fa-save me-2"></i>SALVAR</button>
                            <a href="{% url 'website:index' %}"
                                class="btn btn-link text-decoration-none text-secondary">CANCELAR</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

petshop/pets/templates/pets/exclui.html
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% block title %}Exclusão de Pet{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row d-flex justify-content-center">
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
      <div class="card bg-light border-0 mb-3">
        <div class="card-body text-dark">
          <h5 class="card-title">Exclusão de pet</h5>
          <p class="card-text mb-4">Você tem certeza de que quer apagar o registro do pet <strong>{{ pets.nome }}</strong>? A exclusão será irreversível.</p>

          <form method="post">
            <!-- A tag do Django {% csrf_token %} está relacionada à proteção que o Django provê ao CSRF - Cross Site Request Forgery (um tipo de ataque malicioso) -->
            {% csrf_token %}

            <div class="text-start">
              <button class="btn btn-danger"><i class="fas fa-trash-alt me-2"></i>EXCLUIR</button>
              <a href="{% url 'pets:lista_pets' %}" class="btn btn-link text-decoration-none text-secondary">CANCELAR</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

petshop/pets/templates/pets/lista.html
<!-- Aqui terá um objeto chamado 'pets' contendo todos os pets disponíveis para iteração. -->
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Pets{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Lista de pets</h5>
                    <p class="card-text mb-4">Quadro atualizado de pets cadastrados.</p>

                    {% if pets|length > 0 %}
                    <table class="table table-borderless">
                        <thead class="table-success">
                            <tr>
                                <th scope="col">Nome</th>
                                <th scope="col">Espécie</th>
                                <th scope="col">Raça</th>
                                <th scope="col">Sexo</th>
                                <!-- <th scope="col">Notas</th> -->
                                <th scope="col">Cliente</th>
                                <th scope="col" class="text-end">Opções</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for pets in pets %}
                            <tr>
                                <td>{{ pets.nome }}</td>
                                <td>{{ pets.especie }}</td>
                                <td>{{ pets.raca }}</td>
                                <td>{{ pets.sexo }}</td>
                                <!-- <td>{{ pets.notas }}</td> -->
                                <td>{{ pets.cliente }}</td>

                                <td class="text-end">
                                    <a href="{% url 'pets:atualiza_pets' pk=pets.id %}">
                                        <i class="link-success fas fa-user-edit"></i></a>
                                    <a href="{% url 'pets:deleta_pets' pk=pets.id %}">
                                        <i class="ms-2 link-danger fas fa-user-minus"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <div class="text-center mt-5 mb-5 jumbotron">
                        <h5>Sem pets registrados ainda.</h5>
                    </div>
                    {% endif %}
                    <div class="text-start">
                        <a href="{% url 'pets:cadastra_pets' %}" class="btn btn-secondary"><i
                                class="fas fa-plus me-2"></i>NOVO</a>
                        <a href="{% url 'website:index' %}"
                            class="btn btn-link text-decoration-none text-secondary">INÍCIO</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}