petshop/pets/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from pets.views import PetsCreateView, PetsListView, PetsUpdateView, PetsDeleteView

app_name = 'pets'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /cadastrar
    path('cadastrar/', PetsCreateView.as_view(), name="cadastra_pets"),

    # GET /listar
    path('listar/', PetsListView.as_view(), name="lista_pets"),

    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /pets (pets está definido em url.py petshop)/{pk do objeto}
    path('<pk>', PetsUpdateView.as_view(), name="atualiza_pets"),

    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /pets (pets está definido em url.py petshop)/excluir/{pk do objeto}
    path('excluir/<pk>', PetsDeleteView.as_view(), name="deleta_pets"),
]

petshop/petshop/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    # Interface administrativa.
    path('admin/', admin.site.urls),

    # Inclui as URLs do app 'website'.
    path('', include('website.urls', namespace='website')),

    # Inclui as URLs do app 'services'.
    path('services/', include('services.urls', namespace='services')),

    # Inclui as URLs do app 'pets'.
    path('pets/', include('pets.urls', namespace='pets')),

        # Inclui as URLs do app 'sales'.
    path('sales/', include('sales.urls', namespace='sales')),

    # Inclui as URLs do app 'accounts'
    path('accounts/', include('accounts.urls')),

    # Inclui as URLs de 'login'
    path('accounts/', include('django.contrib.auth.urls')),
]

petshop/sales/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from sales.views import SalesCreateView, SalesListView,SalesUpdateView, SalesDeleteView

app_name = 'sales'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /cadastrar
    path('cadastrar/', SalesCreateView.as_view(), name="cadastra_sales"),

     # GET /listar
    path('listar/', SalesListView.as_view(), name="lista_sales"),

    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /sales/{pk do objeto}
    path('sales/<pk>', SalesUpdateView.as_view(), name = "atualiza_sales"),
    
    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /sales/excluir/{pk do objeto}
    path('sales/excluir/<pk>', SalesDeleteView.as_view(), name="deleta_sales"),
]

petshop/website/urls.py
# Importação das funções definidas no arquivo views.py.
from django.urls import path
from website.views import IndexTemplateView, ClientesListView, ClientesUpdateView, ClientesDeleteView, ClientesCreateView

app_name = 'website'

# A urlpatterns contém a lista de roteamentos de URLs.
urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),
    
    # GET /clientes/cadastrar
    path('clientes/cadastrar', ClientesCreateView.as_view(), name="cadastra_clientes"),
    
    # GET /clientes
    path('clientes/', ClientesListView.as_view(), name="lista_clientes"),
    
    # Para atualizar o objeto, devemos buscá-lo via 'id' ou 'slug'. Também pode ser atualizado através do método get_object().
    # GET/POST /cliente/{pk do objeto}
    path('clientes/<pk>', ClientesUpdateView.as_view(), name = "atualiza_clientes"),
    
    # Para deletar o objeto, o procedimento é parecido com o de atualização.
    # GET/POST /cliente/excluir/{pk do objeto}
    path('clientes/excluir/<pk>', ClientesDeleteView.as_view(), name="deleta_clientes"),
]

petshop/sales/forms.py
from petshop.models import Sales
from django import forms
import datetime

# Formulário de inserção usando ModelForm.
class InsereSalesForm(forms.ModelForm):
    data = forms.DateField(label="Data da venda", initial=datetime.date.today)
    class Meta:
        # Modelo que o Django deve pegar os campos.
        model = Sales
        # Os campos que estarão no formulário serão apresentados através do atributo fields.
        fields = [
            'cliente',
            'pet',
            'servico',
            'preco',
            'data'
        ]

petshop/sales/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from petshop.models import Sales
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from sales.forms import InsereSalesForm


# Impedir acesso se não estiver logado.
@method_decorator(login_required, name='dispatch')
# Utilizando a CreateView para adicionar uma nova venda.
class SalesCreateView(CreateView):
    template_name = "sales/cria.html"
    model = Sales
    form_class = InsereSalesForm
    # O método reverse_lazy() vai traduzir a View em URL. Após adicionar uma venda, haverá um redirecionamento para a página de listagem atualizada.
    success_url = reverse_lazy("sales:lista_sales")


@method_decorator(login_required, name='dispatch')
# Utilizando a ListView para a listagem de vendas.
class SalesListView(ListView):
    template_name = "sales/lista.html"
    model = Sales
    context_object_name = 'sales'

@method_decorator(login_required, name='dispatch')
# Utilizando a UpdateView para a atualização de vendas.
class SalesUpdateView(UpdateView):
    template_name = "sales/atualiza.html"
    model = Sales
    # fields = ['cliente', 'pet', 'servico', 'preco', 'data']
    fields = '__all__'
    context_object_name = 'sales'
    success_url = reverse_lazy("sales:lista_sales")

@method_decorator(login_required, name='dispatch')
# Utilizando a DeleteView para deletar uma venda.
class SalesDeleteView(DeleteView):
    template_name = "sales/exclui.html"
    model = Sales
    context_object_name = 'sales'
    success_url = reverse_lazy("sales:lista_sales")

petshop/sales/templates/sales/atualiza.html
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% load crispy_forms_tags %}

{% block title %}Atualização de Vendas{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Atualizar venda</h5>
                    <p class="card-text mb-4">Atualização dos dados da venda.</p>

                    <form method="post" class="row g-3">
                        <!-- A tag do Django {% csrf_token %} está relacionada à proteção que o Django provê ao CSRF - Cross Site Request Forgery (um tipo de ataque malicioso) -->
                        {% csrf_token %}

                        <!-- {{ form.as_p }} -->
                        {{ form|crispy }}

                        <div class="text-start mt-4">
                            <button class="btn btn-secondary"><i class="fas fa-save me-2"></i>SALVAR</button>
                            <a href="{% url 'sales:lista_sales' %}"
                                class="btn btn-link text-decoration-none text-secondary">CANCELAR</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

petshop/sales/templates/sales/cria.html
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% load crispy_forms_tags %}

{% block title %}Cadastro de Vendas{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Registrar venda</h5>
                    <p class="card-text mb-4">Use os campos abaixo para registar uma nova venda.</p>

                    <form method="post" class="row g-3">
                        <!-- A tag do Django {% csrf_token %} está relacionada à proteção que o Django provê ao CSRF - Cross Site Request Forgery (um tipo de ataque malicioso) -->
                        {% csrf_token %}

                        <!-- {{ form.as_p }} -->
                        {{ form|crispy }}

                        <div class="text-start mt-4">
                            <button class="btn btn-secondary"><i class="fas fa-save me-2"></i>SALVAR</button>
                            <a href="{% url 'website:index' %}"
                                class="btn btn-link text-decoration-none text-secondary">CANCELAR</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

petshop/sales/templates/sales/exclui.html
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% block title %}Deletar Vendas{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row d-flex justify-content-center">
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
      <div class="card bg-light border-0 mb-3">
        <div class="card-body text-dark">
          <h5 class="card-title">Exclusão de venda</h5>
          <p class="card-text mb-4">Você tem certeza de que quer excluir o registro da venda feita para <strong>{{ sales.cliente }}</strong>? A exclusão será irreversível.</p>

          <form method="post">
            <!-- A tag do Django {% csrf_token %} está relacionada à proteção que o Django provê ao CSRF - Cross Site Request Forgery (um tipo de ataque malicioso) -->
            {% csrf_token %}

            <div class="text-start">
              <button class="btn btn-danger"><i class="fas fa-trash-alt me-2"></i>EXCLUIR</button>
              <a href="{% url 'sales:lista_sales' %}" class="btn btn-link text-decoration-none text-secondary">CANCELAR</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

petshop/sales/templates/sales/lista.html
<!-- Aqui terá um objeto chamado 'vendas' contendo todas as vendas disponíveis para iteração. -->
<!-- Estender do template base -->
{% extends "website/_layouts/base.html" %}

{% block title %}Lista de Vendas{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
            <div class="card bg-light border-0 mb-3">
                <div class="card-body text-dark">
                    <h5 class="card-title">Lista de vendas</h5>
                    <p class="card-text mb-4">Quadro atualizado de vendas registradas.</p>

                    {% if sales|length > 0 %}
                    <table class="table table-borderless">
                        <thead class="table-success">
                            <tr>
                                <th scope="col">Cliente</th>
                                <th scope="col">Pet</th>
                                <th scope="col">Serviço</th>
                                <th scope="col">Preço</th>
                                <th scope="col">Data</th>
                                <th scope="col" class="text-end">Opções</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for sales in sales %}
                            <tr>
                                <td>{{ sales.cliente }}</td>
                                <td>{{ sales.pet }}</td>
                                <td>{{ sales.servico }}</td>
                                <td>{{ sales.preco }}</td>
                                <td>{{ sales.data }}</td>

                                <td class="text-end">
                                    <a href="{% url 'sales:atualiza_sales' pk=sales.id %}">
                                        <i class="link-success fas fa-user-edit"></i></a>
                                    <a href="{% url 'sales:deleta_sales' pk=sales.id %}">
                                        <i class="ms-2 link-danger fas fa-user-minus"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <div class="text-center mt-5 mb-5 jumbotron">
                        <h5>Sem vendas registrados ainda.</h5>
                    </div>
                    {% endif %}
                    <div class="text-start">
                        <a href="{% url 'sales:cadastra_sales' %}" class="btn btn-secondary"><i class="fas fa-plus me-2"></i>NOVO</a>
                        <a href="{% url 'website:index' %}" class="btn btn-link text-decoration-none text-secondary">INÍCIO</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}